print('PyDev console: using IPython 7.6.1\n')

import sys; print('Python %s on %s' % (sys.version, sys.platform))
sys.path.extend(['I:\\score', 'I:\\score\\Python\\day01', 'I:\\score\\Python\\day02', 'I:/score'])
import os
# os.chdir()
os.getcwd()
os.chdir(os.path.join(os.getcwd(), "Python/day02"))
os.getcwd()
f = open('test.txt', "w")
f.write("abc")
f.write("*" * 4093)
f.write("_")
os.listdir()
f1 = open("test.txt", 'r')
f1.read()
f1.close()
f.close()
f2 = open("text.txt", "wb")
f2.read()
f2 = open("text.txt", "w+")
f2.read()
f2.write("abc")
f2.write("*" * 4093)
f2.write("-")
f2.close()
# %hist -f test_hist.py
